BimTrack Group Clashes updated enough to be it's own entity and can be install separately
bimone/GroupClashes pull request #1
Opened 2021-04-29 14:18 UTC by francis-bedard-bimoine

Namespace updated
Assembly name changed
Display name changed 
Pluggin name changed to

2021-04-30 14:06 UTC, mgodbout requested changes

2021-04-30 14:06 UTC, mgodbout commented on 2021/nuget.config
> +  </activePackageSource>  <packageSources>    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />    <add key="BIMOne-private" value="BIMOne-private" value="https://www.myget.org/F/bimone-p
Tag value="BIMOne-private" de trop ici

2021-04-30 14:28 UTC, francis-bedard-bimoine commented on 2021/nuget.config
> +  </activePackageSource>  <packageSources>    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />    <add key="BIMOne-private" value="BIMOne-private" value="https://www.myget.org/F/bimone-p
Oui effectivement. Je vais corriger ça

2021-04-30 14:51 UTC, mgodbout approved these changes

2021-05-04 12:37 UTC, AlainBolduc commented on 2017/GroupClashes/GroupClashesInterface.xaml
> -             xmlns:groupClashes="clr-namespace:GroupClashes"
C,est louche que tu puisses enlever le namespace groupClashes et que ca ne te donne pas de warning a cause de la ligne 80 : `<DataTemplate DataType="groupClashes:CustomClashTest">`

pourquoi on veut enlever le namespace?

2021-05-04 12:58 UTC, francis-bedard-bimoine commented on 2017/GroupClashes/GroupClashesInterface.xaml
> -             xmlns:groupClashes="clr-namespace:GroupClashes"
Oups, side effet du adjust namenamespace dans Rider.

2021-05-04 13:04 UTC, francis-bedard-bimoine commented on 2017/GroupClashes/GroupClashesInterface.xaml
> -             xmlns:groupClashes="clr-namespace:GroupClashes"
En fait je viens de voir ce n'est pas dans master non plus

2021-05-10 19:26 UTC, AlainBolduc approved these changes

2021-05-10 19:42 UTC, merged